services:
  - type: web
    name: resume-ocr-service
    env: python
    rootDir: backend
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    build:
      aptPackages:
        - tesseract-ocr
        - poppler-utils
